[project]
name = "dgl-dev"
version = "0.7.2"
requires-python = ">=3.12"
dependencies = [
    "dgl",
    "torch>=2.6.0",
    "tqdm>=4.67.1",
]

[tool.uv.sources]
dgl = { path = "python", editable = true }
